GET http://localhost:3003/api/blogs/
###
GET http://localhost:3003/api/blogs/5ea821c26bd5b215c84d5f83
###
POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1ZWFhZjEwMGIwMmRmODIwZTRjZGZlNWMiLCJpYXQiOjE1ODgyNjI2NjV9.l4-B9deexJoXQ5lt00UKLpwIgaCstKcExKadfNf59l0

{
    "title": "Developer blogger",
	"author": "Masa Mehiläinen",
	"url": "localhost:80",
	"likes": 100
}
###
POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1ZWFhZjEwMGIwMmRmODIwZTRjZGZlNWMiLCJpYXQiOjE1ODgyNjI2NjV9.l4-B9deexJoXQ5lt00UKLpwIgaCstKcExKadfNf59l0

{
    "title": "Other blog",
	"author": "Maisa Cat",
	"url": "localhost:81",
	"likes": 999
}
###
POST http://localhost:3003/api/users/
content-type: application/json

{
    "username": "admin",
	"password": "pasu",
	"name": "Admin Admington"
}
###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "admin",
	"password": "pasu"
}

### Wrong password
POST http://localhost:3003/api/login/
content-type: application/json

{
    "username": "admin",
	"password": "pasup"
}